### ISSUE TITLE
2024

### ISSUE THREAD

**Issue by Artemiy87** [ChiefIntegrator/Steam-GetOnTop#11]
2024

PS C:\GetSM> .\Publish-SteamAppManifests.ps1
Steam is installed in 'f:\progi\gaming\steam'

10 hours more

That's all.

**Comment by VL4DST3R** [comment]
+1 same issue. I think it may be due to not having the user profile public to get the game list?

**Comment by dethzord** [comment]
Anyone figure a solution for this?

**Comment by VL4DST3R** [comment]
This project is very dead. Judging from the last commit, it is 7 years out of date.

If you are like me and only needed this for a single game, you can jury-rig your own appmanifest file by copying one from another game and changing the game id in both the filename and inside of it, where appropriate. Even if other fields are not exactly right i.e. the depot number, it will still let steam detect it and link your game install. From that point just let it verify the files and you're good to go.

**Comment by dethzord** [comment]
I figure it's dead, but there's a chance someone with coding skills finds an interest/need, potentially forks it out or finds a simple edit to the existing script they might share.  More just hopeful.

If it were one game, there would be no need for the script.  You can just tell steam to install whatever the game is, point it to the library, and it will discover, validate, and tell you it's done.  For me, I merged a library (failing drive, moved to a second drive), and seemed to have missed re-adding some games.  Problem is, I missed them, and I didn't realize and now do not know what, if any, might be physically on the drive but not "installed".  It seemed like this would do the job of detecting the game(s) for me at the least, since they'd be missing the appmanifest.  Even if I didn't recreate the manifest with this script, I would still know what to manually reinstall within steam.

It's not the end of the world or anything.  Just mildly hopeful.  Worst case, I've got multiple gigs of wasted space.

**Comment by VL4DST3R** [comment]
> If it were one game, there would be no need for the script

Reinstalling 160gb of stalker 2 files is definitely not what I wanted to deal with so I was hoping this would take care of me as well.


> Worst case, I've got multiple gigs of wasted space.

Why wasted space? In your case wouldn't just a cursory glance at the folder and installing the games again cause steam to detect the already present files?

Also if what I said above is indeed the cause of the issue, then it may not be fixable, unless you change your account to public (which I admit I couldn't be arsed to)

**Comment by dethzord** [comment]
I have nearly 200 titles installed in that particular steam directory.  Or should I say, there are nearly 200 directories listed in that steam library.  Part of the issue is that steam leaves directories when something gets uninstalled.  As such, figuring out what is actually installed vs. what is there but not "installed" vs. what is an empty, leftover directory from an uninstalled game, would be a particularly annoying, tedious task.  Wouldn't be so bad if steam didn't leave things behind (which I understand why), but here we are.

On a side note, I verified my profile on steam is set to public, so that doesn't seem to be the cause of the issue.  As well, I enabled verbose logging, but the log is still useless as it shows the same thing no matter the log level.  Because why not, here's what I get in the log.

```
===========================================================================
Publish-SteamAppManifests.ps1
Executed : Tuesday, December 31, 2024 1:13:02 AM
===========================================================================
01:13:02 AM [.] : Steam is installed in 'e:\games\steam'
```

**Comment by VL4DST3R** [comment]
Yeah, I get the same output, which is also what OP provided.

> Part of the issue is that steam leaves directories when something gets uninstalled. 

Then I'm afraid that this script would not have helped you anyways. From the readme, the method of finding what games are present/installed is using exactly those folder names:


    For each install directory in \SteamApps\Common:

    Try to match against lookup table (fastest, most accurate)
    Try to find app named identically to the install directory name (fast, accurate)

**Comment by dethzord** [comment]
It would help, even if it still required a little manual intervention.  Most everything is going to be installed.  Anything without an appmanifest would get detected (be it an empty directory or one with a game in it).  From there, it would be a short list, and I could easily verify empty vs. not.

In such a case, while not a one and done solution, it would be a very helpful tool.  Certainly better than checking 200 directories by hand.  I don't mind using a little elbow grease, but doing it 100% manually isn't worth the payout of reclaiming some wasted space.  Storage is cheap, ultimately.

**Comment by VL4DST3R** [comment]
The amount of wasted space is very much dependent on what games you have, and at least for me personally I would not want to keep (and potentially even backup) junk in my pc - but i understand what you mean.

Assuming space was not the reason why you needed this script in the first place, why not just go ahead with the nuclear option of reinstalling all games again? I'm assuming this was more or less what you were aiming for given the number of games in your old library.

**Comment by dethzord** [comment]
Space, along with being a little anal retentive about tidying up library, are the main reasons why I am looking for a solution.  As well, the purpose of moving things is to avoid re-downloading the games again.  It would be very counter-productive in that regard, to delete and re-download 420 gigs worth of installed games, just to reclaim what is likely less than 50 gigs of space (potentially MUCH less, but I can't tell for sure and none of it would be an issue if I COULD).

At some point before the end of next year, I'll be switching to linux anyhow and it won't matter, as most of my drives will get wiped.  I refuse to install the privacy nightmare that will be Win11.  I just need to decide on a distro.  Testing Pop!_OS Cosmic right now, but I think I will want to run something with Plasma in the end.  Anyhow, that's going off topic.

**Comment by VL4DST3R** [comment]
>  re-downloading the games again.

I'm pretty sure steam would indeed eventually find the pre-existing files present there and you would achieve essentially what you want - ultimately not redownloading the actual game data again.

In my case my core issue was that I could _not_ attempt a reinstall for the game because I did not have an extra ~160gb free for steam to go past his stupid install step where it must pre-allocate the space needed, even if not needed in that case. Otherwise I would have went ahead with that solution as well and ultimately solve the issue "their" way.

I'm also not going to the mess that is w11 either but linux has no place on my pc. I'm not dealing with that dumpster file of unsupported hardwre, disgusting community and unintuitive folder structure. But I agree, we kinda hijacked this topic, let's call it. 

Also Happy holidays :)

**Comment by dethzord** [comment]
I am confused as to what you need this script for.  From the sound of it, you had Stalker 2 physically present on your drive, but it lacked the appmanifest.  You don't need to recreate the appmanifest; all you need to do is tell steam (which would not see the game as installed) to install the game to the library where you physically have the files.  Steam would do the rest of the work; it would make the new manifest, verify the files, and not download anything at all.  You don't need an extra 160 gigs; the 160 gigs is already present on the drive, and steam would not need to download anything, it would not pre-allocate anything at all.  It would see the existing files and go about its business.

I did exactly what I am describing with Watch_Dogs (the one game I got lucky to find that I didn't "reinstall" after moving).  Steam doesn't need to allocate squat, it just sees the existing things and verifies.  So either you've poorly explained your situation, or you're doing something very wrong.

**Comment by VL4DST3R** [comment]
Re-read my above post because that's exactly what I described: 

> [...]160gb free for steam to go past his stupid install step where it must pre-allocate the space needed, **even if not needed in that case**. Otherwise I would have went ahead with that solution as well and ultimately solve the issue "their" way.
    
When I attempt to install, steam does not let you proceed if you do not have enough free disk space for the game. The stage where it checks if you do indeed have files already present for a game happens only **afterwards**, which I could not reach. You most likely had enough for your game, so you didn't encounter it.

Amusing since essentially this is what I was also suggesting you do with the remainder of your "lost" games.

**Comment by dethzord** [comment]
The missing piece.  While a good bit stupid on steams part, now it makes sense.  Thanks for that clarification.

I wonder if that's something that could be brought up to Valve in their support forum.  A change in the order of operations, or to have it check for files after it believes there is no space.  Either would solve that issue I would think.

My issue is I don't know what games are lost.  I only noticed Watch_Dogs because I had been sitting on the fence about replaying it and was curious as to when I last fired it up.  I knew it was physically installed but was missing from my list.  Other games aren't currently on my radar, so to speak.  Many are just waiting their turn (I've had unplayed games installed for literally years).  So it's difficult to know what is there and what isn't based on directories.  Some of them I might prefer to simply delete.  I was just looking for a way to figure out what's what, and this is the only solution I've found to ease the process (greatly so, if it worked).

Thanks for the discussion.  Maybe the original dev will notice all the activity and pop back in.  Haha.

**Comment by VL4DST3R** [comment]
Yeah, there's only hope lol. As for steam I find it unlikely that I'm the first to encounter this annoyance, I'm just guessing its not high on their priority lost or is a technical limitation of how the process works.

**Comment by ciphernemo** [comment]
I [forked this project](https://github.com/ciphernemo/Steam-GetOnTop) to complete a pull request that fixes issues with reading VDF files, specifically within the ConvertFrom-VDF function. You can download mine to test it. I'm using those functions in my other project [PoE2-Affinity](https://github.com/ciphernemo/PoE2-Affinity).

**Comment by dethzord** [comment]
I just ran it.  I get some errors, but it does eventually pop up the output window with a few things in it.  Problem there is that the columns cannot be expanded, so I can't see what directories it's pointing to.

As well, I do not think this tool will work for my needs in the end.  I have multiple steam libraries across multiple drives.  This only checked one library located in Steam's installation directory.

In the hopes it will still help you and/or anyone else who might want to work  on it, I'll drop the two errors below.  Leaving out the rest of it, as it shouldn't impact anything not seeing the standard output.  Leaving a small bit for context of where the errors show up.  Additionally, if there's any more testing you might want me to try, please let me know.  Even if the project won't meet my needs, I'm happy to help.

```
PS E:\games\steam-getontop\forked> .\Publish-SteamAppManifests.ps1
Steam is installed in 'e:\games\steam'
Get-Member : You must specify an object for the Get-Member cmdlet.
At E:\games\steam-getontop\forked\Publish-SteamAppManifests.ps1:378 char:72
+ ... ($config.InstallConfigStore.Software.Valve.Steam | Get-Member | Where ...
+                                                        ~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-Member], InvalidOperationException
    + FullyQualifiedErrorId : NoObjectInGetMember,Microsoft.PowerShell.Commands.GetMemberCommand

Loading app info from Steam Store...
... 228913 IDs enumerated
Loading AppID Lookup Table from file '.\appLookup.json' ...
... 1062 IDs enumerated
Loading AppIDs for games owned by Local Users...
Could not retrieve owned games for 'ac' - Error: System.Management.Automation.MethodInvocationException: Exception calling "ToInt32" with "1" argument(s): "Input string was not in a correct format." ---> System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at System.String.System.IConvertible.ToInt32(IFormatProvider provider)
   at CallSite.Target(Closure , CallSite , Object , Object )
   --- End of inner exception stack trace ---
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
... 3033 IDs enumerated
Filtering Apps to owned only... (this may take a minute or two)
```

**Comment by ciphernemo** [comment]
> As well, I do not think this tool will work for my needs in the end. I have multiple steam libraries across multiple drives. This only checked one library located in Steam's installation directory.

I also have multiple steam libraries across multiple drives. For multiple libraries, I have a script I made earlier that find them all. You could use this code to change whatever you want to do within the GetOnTop files. It's four functions followed by a section of code that brings it all together. You can pop this directly into PowerShell (or PowerShell ISE) to test it and see if it finds all of your Steam libraries...

```powershell
#finds the Steam install path
function Get-SteamPath
{
	#search for Steam in registry keys
	[string[]]$hive = @("HKCU:", "HKLM:")
	foreach ($h in $hive)
	{
		try
		{
			$key = "$h\Software\Valve\Steam\"
			if (Test-Path -Path $key)
			{
				$steam = Format-ProperPath ((Get-ItemProperty $key).SteamPath)
				if (Test-Path -Path $steam) { return $steam }
			}
		}
		catch
		{
			continue
		}
	}
	#test for default install path
	$pfx86 = "${Env:ProgramFiles(x86)}"
	if (Test-Path -Path "$pfx86\Steam\steam.exe")
	{
		return "$pfx86\Steam\steam.exe"
	}
	#search drives for steam.exe file
	else
	{
		Write-Host "Steam client not within the Registry or default location. Searching your drives for Steam..."
		#set up system drive exclusions for search
		[string[]]$paths = @($Env:SystemRoot, $Env:ProgramData, $Env:TEMP, "$Env:SystemRoot\Temp", "$Env:SystemDrive\Recovery")
		$paths += ("$Env:USERPROFILE\GoogleDrive", "$Env:USERPROFILE\Box")
		if ($Env:OneDrive) { $paths += $Env:OneDrive }
		#get all drives on the system
		[string[]]$driveLetters = Get-PSDrive | Select-Object -ExpandProperty "Name" | Select-String -Pattern '^[a-z]$'
		[string[]]$results = @()
		foreach ($d in $driveLetters)
		{
			$d = $d + ":\"
			Write-Host "Searching $d drive..."
			#recursively search a drive and add matches to results
			if ($items = Get-ChildItem -Path $d -Filter "steam.exe" -Exclude $paths -Recurse)
			{
				foreach ($item in $items)
				{
					$results += $item.FullName
				}
			}
		}
		if ($results.Count -gt 0)
		{
			return $results
		}
		else
		{
			#no results found
			Write-Host "Steam not found on the local system. Exiting..."
			Start-Sleep -Seconds 6
			exit
		}
	}
}

#formats a string to trim leading and trailing quote marks
function Format-MemberString
{
	param
	(
		[parameter(Mandatory = $true)]
		[string]$myMember
	)
	return (($myMember).Substring(1, $myMember.Length - 2))
}

#formats a path to replace all forward slashes with back slashes and return its proper capitalization
function Format-ProperPath
{
	param
	(
		[parameter(Mandatory = $true)]
		[string]$Path
	)
	$Path = $Path.Replace('/', '\')
	$properPath = [String]::Empty
	if (!((Test-Path $Path -PathType Leaf) -or (Test-Path $Path -PathType Container)))
	{
		return $Path
	}
	foreach ($branch in $Path.Split("\"))
	{
		if ($properPath -eq "")
		{
			$properPath = $branch.ToUpper() + "\"
			continue
		}
		$properPath = [System.IO.Directory]::GetFileSystemEntries($properPath, $branch)[0];
	}
	return $properPath;
}

#parses a VDF and converts it to a custom object
#	example: $vdf = ConvertFrom-VDF -source (Get-Content "C:\localconfig.vdf")
function ConvertFrom-VDF
{
	param
	(
		[parameter(Mandatory = $true)]
		[ValidateNotNullOrEmpty()]
		[System.String[]]$Source
	)
	$root = New-Object -TypeName PSObject
	$chain = [ordered]@{}
	$treeDepth = 0
	$parent = $root
	$element = $null
	$i = 0
	foreach ($line in $Source)
	{
		#make one to two matches per line of quoted sections, separate by tabs only when next to quote marks,
		#	match empty and single character quoted sections,
		#	include escaped quotes \" in matches but don't make separate matches for \"",
		#	and include leading and trailing quote marks for safety as they will be removed when converting back to VDF
		$pattern = '(?<=^|\t|{|\n)"((?:[^"\\]|\\[\\"])*)"(?=\t|\n|$|})'
		$quotedElements = (Select-String -Pattern $pattern -InputObject $line -AllMatches).Matches
		#create a new sub object
		if ($quotedElements.Count -eq 1)
		{
			$element = New-Object -TypeName PSObject
			Add-Member -InputObject $parent -MemberType NoteProperty -Name $quotedElements[0].Value -Value $element
		}
		#create a new string hash
		elseif ($quotedElements.Count -eq 2)
		{
			Add-Member -InputObject $element -MemberType NoteProperty -Name $quotedElements[0].Value -Value $quotedElements[1].Value
		}
		elseif ($line -match "{")
		{
			$chain.Add($treeDepth, $element)
			$parent = $chain.$treeDepth
			$treeDepth++
		}
		elseif ($line -match "}")
		{
			$treeDepth--
			$treeDepthLower = $treeDepth - 1
			$parent = $chain.$treeDepthLower
			$element = $parent
			$chain.Remove($treeDepth)
		}
		$i++
	}
	return $root
}


#get all Steam install locations, then all Steam libraries
[string[]]$libPaths = @()
[string[]]$steamPaths = Get-SteamPath
foreach ($mySteamPath in $steamPaths)
{
	#get all Steam library paths
	$vdfLibraryFile = $mySteamPath + "\steamapps\libraryfolders.vdf"
	Write-Host "`nPath to library config file: $vdfLibraryFile `n"
	$vdfLibraryContent = Get-Content $vdfLibraryFile
	$vdfLibraryObject = ConvertFrom-VDF -Source $vdfLibraryContent
	[string[]]$libIDs = @()
	$vdfLibraryObject.'"libraryfolders"'.PSObject.Properties | ForEach-Object { $libIDs += $_.Name }
	foreach ($i in $libIDs)
	{
		$thisPath = Format-MemberString ($vdfLibraryObject.'"libraryfolders"'.$i.'"path"')
		$thisPath = $thisPath.Replace("\\", "\")
		if (Test-Path "$thisPath\steamapps\common")
		{
			$id = $i.Replace("`"", "")
			Write-Host "Found library ID $id with path $thisPath"
			$libPaths += $thisPath + "\steamapps\common"
		}
	}
}

#this will display all Steam library paths
Write-Host "`nResults..."
foreach ($s in $libPaths) { Write-Host "Steam Library: $s" }
```

**Comment by dethzord** [comment]
Your script did work, but your suggestion to use it falls on ignorant ears.  I can't code, and would not know how to add it all together.  I can look at a script and get and idea of what it does (or at the least, get a good idea if I *shouldn't* run something).  I can poke around and make minor adjustments (paths, some values, etc).  But that's about it, unfortunately.

**Comment by ciphernemo** [comment]
> Your script did work, but your suggestion to use it falls on ignorant ears. I can't code, and would not know how to add it all together. I can look at a script and get and idea of what it does (or at the least, get a good idea if I _shouldn't_ run something). I can poke around and make minor adjustments (paths, some values, etc). But that's about it, unfortunately.

No worries. I copied this project to my local system, debugged it, and I think it's working. Well, it's working for my Steam install with multiple Steam libraries. So I published the changes to my fork of this project: https://github.com/ciphernemo/Steam-GetOnTop

You can download a Zip of it here: https://github.com/ciphernemo/Steam-GetOnTop/releases/tag/v1.0

Let me know if it's working. I don't use this tool, but I did use some of its code for my other scripts. So I'm not sure about everything that's it's supposed to be doing, but I did resolve all of the errors I noticed and it did help me resolve a couple of Steam app installs where the folder was missing the game, or where the game files were there but Steam didn't think it was installed. So I assume that's a win. 😊

**Comment by dethzord** [comment]
It's been running now for over 30 minutes, and still going.  It looks like it is related to character checking for install directories, I am guessing by the output.

`Trying (Name -match [Install Directory, Split by '_']) ...`

I assume it's just being thorough, yes?  And will need to cycle through the list of defined characters for each library?  Reasonable for it to take a while, if that's what it must do.  We're not working with some fast sql database or something, just a script following functions.  

It's already doing much more than anything I've run so far.  -- Oo, and as I type this, the sanity check just popped!  Let me see what it gives...  Will update soon.

--edit

It's done.  Spit out much more than before.  Still have the hard part of being unable to adjust the size of the columns in the check window, though maybe I don't actually need to based on the output.  It looked cut off, but I think it's just showing the library path, not the game's expected path.

It clearly identified about 92 entries, and has about that many (maybe a little less) of ones that it is clueless about.  Doing a hand check on a couple from either group, I know some (most?) are certainly installed, some are not.  I can see, at least, that every listing is for the same library.

At this point, I feel like the script will not be helpful.  It seems to suggest I need to make an appmanifest for things that are absolutely there, and have a verified manifest.  Likely a rewrite would be needed?  I dunno.  But it's not something I would put your direction, unless you're having fun tinkering.  You've already done a good bit and made the thing work.

On a side note, thanks for your effort.  People that do things like you did here are what make these kinds of things great.  Not your project, but here you are, offering your skills and time to help fix it.  Respek Knuckles.

**Comment by ciphernemo** [comment]
> It's done. Spit out much more than before. Still have the hard part of being unable to adjust the size of the columns in the check window, though maybe I don't actually need to based on the output. It looked cut off, but I think it's just showing the library path, not the game's expected path.
> 
> It clearly identified about 92 entries, and has about that many (maybe a little less) of ones that it is clueless about. Doing a hand check on a couple from either group, I know some (most?) are certainly installed, some are not. I can see, at least, that every listing is for the same library.

Good to hear it's getting better. Since I started working on this and posted, I've dumped more time into cleaning up all script files instead of just the Publish one. And I'll keep posting commits/updates to mine: https://github.com/ciphernemo/Steam-GetOnTop

I've learned that if you run the Initialise-SteamAppLookup script (it's obvious the original author uses British English instead of American English) it's an optional one time run for users to generate an app lookup file that will speed up the Publish-SteamAppManifests script.

I'm still updating it and making changes...

**Comment by dethzord** [comment]
Awesome!  I'll keep an eye on your fork and see where it goes.

Since you mentioned it above, I tried running the lookup script.  It just spews errors at me.  First error is related to VDFTools module not being found, which I am guessing is the cause of all the rest of the errors.  Looks like they're path related because Get-SteamPath isn't valid (guessing that's what the module handles).

**Comment by ciphernemo** [comment]
> Awesome! I'll keep an eye on your fork and see where it goes.
> 
> Since you mentioned it above, I tried running the lookup script. It just spews errors at me. First error is related to VDFTools module not being found, which I am guessing is the cause of all the rest of the errors. Looks like they're path related because Get-SteamPath isn't valid (guessing that's what the module handles).

I've updated it! A lot of fixes. I now have a good grasp on what each script needs to do. Everything should work much better now for version 1.1. I also updated the Readme. Fork: https://github.com/ciphernemo/Steam-GetOnTop

Make sure you delete your existing files for Steam-GetOnTop locally, then download the Zip file and extract it.

**Comment by dethzord** [comment]
Ran Create first, then Publish.  Per the log, it found the following:

`12:07:33 AM [.] : ... query complete. 129 missing app manifest(s) (129 total), 62 unmatched`

The sanity check suggests they're all in the same library (listed as "g:\games\steam").  I have a small handful of games on my m.2 drive, and verified that nothing installed there is listed.

Per Steam, I have 126 games installed currently across all libraries.

At this point, I will still need to hand check every single entry it has found to verify what is correct and what is not.  There are 191 directories in my library on my G drive.  I know many of them are going to be leftover data (saves, shaders, etc) with no game installed.  It appears that those are not showing up in the sanity check, which is good.  But so far, the handful that I've checked are all installed just fine, Steam sees them fine, and they have a valid appmanifest.  As such, it's not really going to do what I believe it is supposed to do, since it is identifying things (apparently that entire library) that it should see as valid and not in need of a manifest.

I did get an error early in running Publish, but I am fairly certain it is not related to the result:

```
12:07:29 AM [.] : Loading AppIDs for games owned by Local Users...
12:07:29 AM [^] : Could not retrieve owned games for '12584174' - Error: System.Management.Automation.ParameterBindingException: A positional parameter cannot be found that accepts argument '76561197972849902'.
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
12:07:29 AM [^] : Could not retrieve owned games for '75675427' - Error: System.Management.Automation.ParameterBindingException: A positional parameter cannot be found that accepts argument '76561198035941155'.
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
12:07:29 AM [^] : Could not retrieve owned games for 'ac' - Error: System.Management.Automation.MethodInvocationException: Exception calling "ToInt32" with "1" argument(s): "Input string was not in a correct format." ---> System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at System.String.System.IConvertible.ToInt32(IFormatProvider provider)
   at CallSite.Target(Closure , CallSite , Object , Object )
   --- End of inner exception stack trace ---
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
12:07:29 AM [.] : ... 0 IDs enumerated
```

**Comment by BlueRaja** [comment]
The new script did not work for me. I get the following error:

```
Loading AppIDs for games owned by Local Users...
Could not retrieve owned games for '1503090' - Error: System.Management.Automation.ParameterBindingException: A positional parameter cannot be found that accepts argument '76561197961768818'.
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
... 0 IDs enumerated
```

I'd prefer to continue this discussion on the 'issues' page for your version of the script, if you'll open it up for issues.

[Edit] I managed to fix that error by adding quotes to [this line](https://github.com/ciphernemo/Steam-GetOnTop/blob/master/Publish-SteamAppManifests.ps1#L410), but the tool still doesn't find an ID for about 1/3rd of my games.

**Comment by ciphernemo** [comment]
> The new script did not work for me. (...)
> 
> I'd prefer to continue this discussion on the 'issues' page for your version of the script, if you'll open it up for issues.
> 
> [Edit] I managed to fix that error by adding quotes to [this line](https://github.com/ciphernemo/Steam-GetOnTop/blob/master/Publish-SteamAppManifests.ps1#L410), but the tool still doesn't find an ID for about 1/3rd of my games.

Thanks for letting me know, and thanks for finding one fix to help with the web request even if it didn't resolve the entire issue. I'll get back to this project soon, as I have another I'm trying to finish up right now.

Also, sure, I just enabled Issues and Discussions as well. 😊 I didn't realize GitHub disabled Issues by default. I'm no GitHub pro, so muddle through it best I can sometimes.
